# Generated by Django 5.1.7 on 2025-03-11 09:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmake_name', models.CharField(max_length=32, unique=True)),
                ('carmake_name_en', models.CharField(max_length=32, null=True, unique=True)),
                ('carmake_name_ru', models.CharField(max_length=32, null=True, unique=True)),
                ('carmake_image', models.ImageField(upload_to='car_make_images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
                ('category_name_en', models.CharField(max_length=32, null=True, unique=True)),
                ('category_name_ru', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('owner', 'owner'), ('client', 'client')], default='client', max_length=24)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
            bases=('car_shop.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_account', models.CharField(choices=[('базовый', 'базовый'), ('стандарт', 'стандарт'), ('продвинутый', 'продвинутый')], default='базовый', max_length=32)),
                ('status_owner', models.CharField(choices=[('owner', 'owner'), ('client', 'client')], default='owner', max_length=24)),
            ],
            options={
                'verbose_name_plural': 'owners',
            },
            bases=('car_shop.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('car_body', models.CharField(choices=[('седан', 'седан'), ('универсад', 'универсал'), ('внедорожник', 'внедорожник'), ('пикап', 'пикап'), ('хетчбек', 'хетчбек'), ('крассовер', 'крассовер')], default='седан', max_length=36)),
                ('engine', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('гибрид', 'гибрид'), ('электр', 'электр')], default='бензин', max_length=12)),
                ('drive', models.CharField(choices=[('полный', 'полный'), ('задний', 'задний'), ('передний', 'передний')], default='полный', max_length=32)),
                ('transmission', models.CharField(choices=[('автамат', 'автамат'), ('механика', 'механика')], default='механика', max_length=24)),
                ('modification', models.CharField(choices=[('1.8', '1.8'), ('2.0', '2.0'), ('2.4', '2.4'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.4', '3.4')], default='1.8', max_length=24)),
                ('rule', models.CharField(choices=[('рул слева', 'рул слева'), ('рул справа', 'рул справа')], default='слева', max_length=16)),
                ('video', models.URLField(blank=True, null=True)),
                ('address_country', models.CharField(max_length=64)),
                ('address_city', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color', models.FileField(upload_to='')),
                ('state', multiselectfield.db.fields.MultiSelectField(choices=[(' хорошее', ' хорошее'), (' идеальное', ' идеальное'), (' аварийное / не на ходу', ' аварийное / не на ходу'), (' новое', ' новое')], max_length=64)),
                ('mileage', models.CharField(max_length=62)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('appearance', multiselectfield.db.fields.MultiSelectField(choices=[('обвес', 'обвес'), ('багажник', 'багажник'), ('панорамная крыша', 'панорамная крыша'), ('тонировка', 'тонировка'), ('спойлер', 'спойлер')], max_length=72)),
                ('salon', multiselectfield.db.fields.MultiSelectField(choices=[('комбинированный', 'комбинированный'), ('велюр', 'велюр'), ('шторки', 'шторки'), ('кожа', 'кожа')], max_length=72)),
                ('security', multiselectfield.db.fields.MultiSelectField(choices=[('подушки безопасности', 'подушки безопасности'), ('антипробуксовочная система', 'антипробуксовочная система'), ('камера 360', 'камера 360')], max_length=72)),
                ('stock_kyrgyzstan', models.CharField(choices=[('в наличие', 'в наличие'), ('на заказ', 'на заказ'), ('в пути', 'в пути')], default='в наличие', max_length=24)),
                ('customs_kyrgyzstan', models.CharField(choices=[('растаможен', 'растаможен'), ('не растаможен', 'не растаможен')], default='растаможен', max_length=64)),
                ('register_country', models.CharField(choices=[('Кыргызстан', 'Кыргызстан'), ('не стоит в учете', 'не стоит в учуте')], max_length=34, verbose_name='страна регистрации')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('change', multiselectfield.db.fields.MultiSelectField(choices=[('обмен не предлагать', 'обмен не предлагать'), ('рассмотрю варианты', 'рассмотрю варианты'), ('обмен на недвижимость', 'обмен на недвижимость')], max_length=82)),
                ('rassrochka', models.BooleanField(default=False)),
                ('other', models.CharField(choices=[('свежепригнан', 'свежепригнан'), ('налог уплачен', 'налог уплачен'), ('техосмотр пройден', 'техосмотр пройден'), ('вложений не требует', 'вложений не требует')], default='техосмотр пройден', max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carmake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmake', to='car_shop.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_image')),
                ('car_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='car_shop.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel_name', models.CharField(max_length=32)),
                ('carmodel_name_en', models.CharField(max_length=32, null=True)),
                ('carmodel_name_ru', models.CharField(max_length=32, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.carmake')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.carmodel'),
        ),
        migrations.AddField(
            model_name='carmake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='car_shop.category'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.car')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=32)),
                ('caremodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.carmodel')),
                ('carmake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.carmake')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_shop.generation'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='car_shop.car')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_shop.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_number', models.CharField(max_length=64)),
                ('tex_passport_picture', models.ImageField(blank=True, null=True, upload_to='tex_passport_picture')),
                ('car_number', models.CharField(max_length=64)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_shop.car')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('social_network', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='car_shop.owner')),
            ],
        ),
    ]
